### ISSUE TITLE
The example Path Planning for a Simple Car doesn't seem to work.

### ISSUE THREAD

**Issue by Evil-sword** [jckantor/ND-Pyomo-Cookbook#34]
When I tried to run Path Planning for a Simple Car, it failed. I received that massage.
>ValueError                                Traceback (most recent call last)
<ipython-input-9-d3e3c5f72a2d> in <module>()
&emsp;&emsp;71 # transform and solve
&emsp;&emsp;72 TransformationFactory('dae.finite_difference').apply_to(m, wrt=m.t, nfe=30)
---> 73 SolverFactory('ipopt').solve(m).write()
1 frames
/usr/local/lib/python3.7/dist-packages/pyomo/opt/base/solvers.py in solve(self, *args, **kwds)
    &emsp;&emsp;633                             result,
    &emsp;&emsp;634                             select=self._select_index,
--> 635                             default_variable_value=self._default_variable_value)
    &emsp;&emsp;636                         result._smap_id = None
    &emsp;&emsp;637                         result.solution.clear()
/usr/local/lib/python3.7/dist-packages/pyomo/core/base/PyomoModel.py in load_from(self, results, allow_consistent_values_for_fixed_vars, comparison_tolerance_for_fixed_vars, ignore_invalid_labels, id, delete_symbol_map, clear, default_variable_value, select, ignore_fixed_vars)
    &emsp;&emsp;236                 raise ValueError("Cannot load a SolverResults object "
    &emsp;&emsp;237                                  "with bad status: %s"
--> 238                                  % str(results.solver.status))
    &emsp;&emsp;239         if clear:
    &emsp;&emsp;240             #
ValueError: Cannot load a SolverResults object with bad status: error

I tried to find out why, but there didn't seem to be a reliable solution on the Internet. So I wonder why.

**Comment by DiegoRomeres** [comment]
I have the same problem. Can the authors please check if the example works on their end and fix it if they confirm that it doesn't?

**Comment by jckantor** [comment]
Yes, this does work on this end. I haven't been able to reproduce the error. If this persists, check if ipopt has been installed and let me know.
