### ISSUE TITLE
Correct kB in Maximizing Concentration of an Intermediate in a Batch Reactor

### ISSUE THREAD

**Issue by kookma** [jckantor/ND-Pyomo-Cookbook#36]
In https://jckantor.github.io/ND-Pyomo-Cookbook/06.02-Maximizing-Concentration-of-an-Intermediate-in-a-Batch-Reactor.html

Under 6.2 the value of `kB` is wrongly reported as `kA` see

![image](https://user-images.githubusercontent.com/830394/130321887-62658549-d720-4717-9dcd-2c0e95d67b13.png)

**Comment by jckantor** [comment]
Thanks for the careful reading and check. Now fixed (sorry for the delay.)  The cookbook is now updated to JupyterBook.

**Comment by kookma** [comment]
Thank you Jeffry for all your great works.
This is a very useful resource and it is well documented.
I use this cookbook in my class (undergrad ChE).
