### ISSUE TITLE
Possible error in 4.2 Machine Bottleneck documentation

### ISSUE THREAD

**Issue by mriepi** [jckantor/ND-Pyomo-Cookbook#39]
I might have found an issue in "4.2.5.2 Decision variables" of the Machine Bottleneck example.

At the end of this paragraph, there are two constrains given to avoid colliding machine allocations.

1) The indices i,j and j,k are confused here between text and equations.
2) To my understanding, the Boolean variable y_i,j must be negated for the two constraints to work properly. Alternatively, the `M*y` and `M*(1-y)` term could be swapped between the equations. This way, both equations hold `TRUE` if there is no overlapping and they hold `TRUE` and `FALSE`, if there is an overlapping, which is what we want.

Despite this, great documentation and a great help for understanding Pyomo!

Kind regards

**Comment by jckantor** [comment]
Thanks the careful reading and catching this. It's now fixed.
