### ISSUE TITLE
error in 4.2.8 and 4.2.9 (caused by Var m.z ?)

### ISSUE THREAD

**Issue by mriepi** [jckantor/ND-Pyomo-Cookbook#40]
Ich receive the error message when running 4.2.8:

<img width="630" alt="Bildschirmfoto 2022-03-09 um 16 18 41" src="https://user-images.githubusercontent.com/99977874/157471644-c1bbc0b5-6ee6-4367-bb15-c8fb20fffb08.png">

**Comment by jckantor** [comment]
Yes, the problem was accessing the pyomo object rather than retrieving the value. This is fixed (sorry for the delay).  Thanks!
