### ISSUE TITLE
Remove pyomo.extras from installation instructions

### ISSUE THREAD

**Issue by blnicho** [jckantor/ND-Pyomo-Cookbook#41]
The "Installing Pyomo" notebook (https://github.com/jckantor/ND-Pyomo-Cookbook/blob/master/notebooks/01.01-Installing-Pyomo.ipynb) instructs users to install `pyomo.extras` from conda-forge. This package is no longer maintained and `pyomo.extras` has been deprecated and removed from the main Pyomo repo. 

I recommend removing this line from the notebook and pointing users to [Pyomo's installation instructions](https://pyomo.readthedocs.io/en/stable/installation.html#conditional-dependencies) if they need any of the optional dependencies. My guess is that a standard conda install will already include any optional Pyomo dependencies used in these notebooks.

**Comment by jckantor** [comment]
pyomo.extras has been removed, and readers are provided a link to the Pyomo installation instructions.  I also took this opportunity to convert the repository to JupyerBook. Thanks for updates!
