### ISSUE TITLE
Issue on page /notebooks/02.01-Production-Models-with-Linear-Constraints.html

### ISSUE THREAD

**Issue by alex-klimov** [jckantor/ND-Pyomo-Cookbook#47]
Throughout the article the definition of the problem claims the product X can be sold for $270 and Y for $210.

However, in the model the profit is defined as:
```python
# declare objective
model.profit = Objective(
    expr = 40*model.x + 30*model.y,
    sense = maximize)
```

Do I understand correctly that this definition defines selling price for product X to be $40 and for product Y to be $30?

**Comment by adowling2** [comment]
I believe that $40 and $30 are the net profit per product, i.e., selling price minus production and raw material costs.

**Comment by alex-klimov** [comment]
Yes, that is even called out in the first example. I just missed it. Thanks!

P.S. Just for the illustration purposes it might make code more readable have product unit margin to be specifically defined as:
```python
product_x_unit_margin = 270 - (100 + 50 + 2*40)
...

model.profit = Objective(
    expr = product_x_unit_margin * model.x + product_y_unit_margin * model.y,
    sense = maximize)
```
